### ISSUE TITLE
Error when creating new command

### ISSUE THREAD

**Issue by UnbreakableKid** [Redstoneguy129/Deno-Discord-Slash-Commands#1]
Hi, when trying to create a new command, the request returns with the following
![image](https://user-images.githubusercontent.com/29483407/118404754-1c276880-b66c-11eb-90e7-3c8db621417d.png)

Could it be that on the createApplicationCommand function it doesn't have the Content-Type header? Or am I missing something?

Getting the commands works flawlessly, only the creating (and probably the others) gives out this error

**Comment by Redstoneguy129** [comment]
Thanks for the issue, i will fix this. There seems to have been an API update.
